### ISSUE TITLE
体重と身長10倍されちゃう問題

### ISSUE THREAD

**Issue by ToYeah** [dai65527/pokedex_vue#9]
フシギダネの身長が0.7kgなのにapiで7にされてるから7mで出力される
0.1倍で数字は出るけど、少数点があるポケモンとないポケモンで表記がぶれるのが気になる
例:
身長:  10m  体重:  20.5kg
↓
身長:  10.0m  体重:  20.5kg

**Comment by dai65527** [comment]
PokeInfoに入れる前に0.1倍しておきますね！
表記については、PokeInfoにはnumberで入れておいて、表示する時にフォーマットを合わせる方が良いと思います。（string型にすると誤解が生じるし変な値が入る恐れがあります）
